### ISSUE TITLE
Elk is leaking threads

### ISSUE THREAD

**Issue by leechuck** [klinovp/elk#4]
Elk seems to be leaking threads. While this would not be a problem when only using Elk to classify one ontology and then shutting down, it becomes a problem when running Elk for a long time. In Aber-OWL, we have Elk running for weeks without ever shutting down the JVM, so making Elk computation threads daemon threads leads to problems after a while as the thread ulimit will be exhausted (we hit 64k threads after a few days in Aber-OWL).
The issue seems to be with https://github.com/klinovp/elk/blob/e34f6b2e0024e96949366560ef4b8ce34ebf1ea5/elk-util-parent/elk-util-concurrent/src/main/java/org/semanticweb/elk/util/concurrent/computation/ComputationExecutor.java#L86 and I wonder if it could be removed safely (so that computation threads properly shut down after execution is complete).

**Comment by leechuck** [comment]
A bit more detail on this issue, as it may be related to threads not properly releasing resources, not only the daemon status of the threads:
when the JVM dies (with a core dump as it hits the ulimit), we get a dump file with lines like that:
  0x00007f18c1db7000 JavaThread "elk-reasoner-thread-5" daemon [_thread_blocked, id=535802, stack(0x00007f17cd0e0000,0x00007f17cd1e1000)]
  0x00007f18c1db5000 JavaThread "elk-reasoner-thread-4" daemon [_thread_blocked, id=535801, stack(0x00007f17cd1e1000,0x00007f17cd2e2000)]
  0x00007f18c1db3000 JavaThread "elk-reasoner-thread-3" daemon [_thread_blocked, id=535800, stack(0x00007f17cd2e2000,0x00007f17cd3e3000)]
  0x00007f18c1db1000 JavaThread "elk-reasoner-thread-2" daemon [_thread_blocked, id=535799, stack(0x00007f17cd3e3000,0x00007f17cd4e4000)]
  0x00007f18c1daf000 JavaThread "elk-reasoner-thread-1" daemon [_thread_blocked, id=535798, stack(0x00007f17cd4e4000,0x00007f17cd5e5000)]

There are 32k of them, while ulimit -u is 64k, but this may be due to daemonizing them.

**Comment by ykazakov** [comment]
Thanks for your report! I can confirm, there is a problem here.
I do not think it has much to do with the daemon status of the threads.
For some reason the ThreadPoolExecutor (which ComputationExecutor extends) creates more threads than it should: according to the documentation it should create a maximum number of threads specified. I will investigate.

**Comment by ykazakov** [comment]
Hi, I am sorry, my previous test had a bug. I don't think I can reproduce the problem you describe.
I made the following test with the pizza ontology, where I query satisfiability of a complex class 10000 times (the same class, but ELK does not cache the result). For me ELK (v.0.4.2) never creates more than 4 worker threads (I have 4 virtual cores on my laptop). Can you try running it on your machine:

public class QueryingClassSatisfiability {

	public static void main(String[] args) throws OWLOntologyCreationException {
		OWLOntologyManager man = OWLManager.createOWLOntologyManager();
		OWLDataFactory dataFactory = man.getOWLDataFactory();

		// Load your ontology.
		OWLOntology ont = man.loadOntologyFromOntologyDocument(new File("/path/to/pizza.owl"));

		// Create an ELK reasoner.
		OWLReasonerFactory reasonerFactory = new ElkReasonerFactory();
		OWLReasoner reasoner = reasonerFactory.createReasoner(ont);

		for (int j = 0; j < 10000; j++) {
			// Create your desired query class expression. In this example we
			// will query ObjectIntersectionOf(A ObjectSomeValuesFrom(R B)).
			PrefixManager pm = new DefaultPrefixManager("http://www.co-ode.org/ontologies/pizza/pizza.owl#");
			OWLClass A = dataFactory.getOWLClass(":Margherita", pm);
			OWLObjectProperty R = dataFactory.getOWLObjectProperty(":hasTopping", pm);
			OWLClass B = dataFactory.getOWLClass(":MeatTopping", pm);
			OWLClassExpression query = dataFactory.getOWLObjectIntersectionOf(A,
					dataFactory.getOWLObjectComplementOf(dataFactory.getOWLObjectSomeValuesFrom(R, B)));
			System.out.println("isSatisfiable(" + query + ") = " + reasoner.isSatisfiable(query));
		}

		// After you are done with all queries, do not forget to free the
		// resources occupied by the reasoner
		reasoner.dispose();
	}

}

**Comment by ykazakov** [comment]
Could it be that you create a reasoner many times without disposing it?

**Comment by ykazakov** [comment]
Another question: in you dump file, what are the names of the threads? Do they get continuous like

elk-reasoner-thread-1
elk-reasoner-thread-2
elk-reasoner-thread-3
...
elk-reasoner-thread-32000

or do some of the thread names repeat?
If you have something like elk-reasoner-thread-32000 then Java probably cannot correctly determine the number of cores on your machine. Do you see in the log how many workers ELK uses for the computation? It should print something like "Loading of Axioms using X workers". What is X in your case?

**Comment by leechuck** [comment]
Thank you for looking into this. I did some more testing, and it is indeed an AberOWL problem; I apologize for opening this issue without sufficient testing.
The number of threads created per reasoner instance is 64 in our case, which is as expected; we had received a lot of simultaneous new ontology additions off of which spawned new reasoners, and this caused our thread limit to be exhausted. We get threads named elk-reasoner-thread-[1-64], as expected.
